### ISSUE TITLE
Добавить в stylelint правило "selector-class-pattern" и запретить использовать дефис

### ISSUE THREAD

**Issue by denisx** [core-ds/arui-presets-lint#15]
Наличие дефиса в классах:

Увеличивает размер css и js файла в распакованном виде
При создании алиасов в js, требует дополнительные кавычки
При некоторых настройках вебпака, в js ещё и создаётся копия алиаса в camelCase, вдобавок к пункту 2.

## Актуальное поведение
js сборка:
![Screenshot 2024-08-14 at 19 09 39](https://github.com/user-attachments/assets/3bfca8b5-5c20-408c-a73b-cba999e60171)

## Ожидаемое поведение
будут 'чистые' ключи, как первые 3 в скриншоте.

Предложение по дефолтному именованию: `camelCase`. В сложных случаях - `snake_case`

## Мотивация изменений

Не критично для резких исправлений, но при должном упорстве подсушивает вес сборки.

ПР https://github.com/core-ds/arui-presets-lint/pull/14

**Comment by kiskv** [comment]
https://github.com/core-ds/arui-presets-lint/releases/tag/v7.6.0
