### ISSUE TITLE
конфликт правил @typescript-eslint/consistent-type-imports и import/no-duplicates

### ISSUE THREAD

**Issue by jkikksa** [core-ds/arui-presets-lint#17]
например есть такой код
``` 
import webpack, { LoaderContext} from 'webpack';
```
такие импорты типов правило @typescript-eslint/consistent-type-imports требует переписать на

```
import type webpack from 'webpack';
import type { LoaderContext} from 'webpack';
```
что конфликтует с правилом import/no-duplicates

**Comment by jkikksa** [comment]
если же прогонять через eslint --fix, то вообще получается невалидный код
```
import type webpack, { type type LoaderContext} from 'webpack';
```

**Comment by kiskv** [comment]
```import webpack, { type LoaderContext } from 'webpack'``` не так должно быть разве? Именно автофикс так работает?

**Comment by KalashnikovTV** [comment]
Ну с автофиксом я ничего не поделаю, некоторые моменты действительно ручками требуется править
