### ISSUE TITLE
Запрет использования React.FC

### ISSUE THREAD

**Issue by KalashnikovTV** [core-ds/arui-presets-lint#24]
На сколько я знаю, в newclick обсуждали, что следует отказаться от использования FC. Поэтому создаю обсуждение, чтобы при поддержке этого предложения, я запретил использование этого типа

https://github.com/facebook/create-react-app/pull/8177
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/
https://www.reddit.com/r/reactjs/comments/vx5qpa/is_fc_still_discouraged/

**Comment by KalashnikovTV** [comment]
@heymdall-legal @qrik116 @kiskv @Hydrock @alterfo

**Comment by qrik116** [comment]
Интересно узнать историю в newclick, какой был негативный опыт
