### ISSUE TITLE
Уточнить правило selector-pseudo-class-no-unknown для stylelint

### ISSUE THREAD

**Issue by e-ogri** [core-ds/arui-presets-lint#34]
В многих проектах видел, что переопределяется правило "selector-pseudo-class-no-unknown", так чтобы можно было использовать псевдо класс global. 

## Актуальное поведение
Псевдо класс global нельзя использовать в css коде
https://github.com/core-ds/arui-presets-lint/blob/master/stylelint/index.js#L31
`'selector-pseudo-class-no-unknown': true,`

## Ожидаемое поведение
Псевдо класс global разрешено использовать, но другие неизвестные псевдо классы нельзя
```javascript
'selector-pseudo-class-no-unknown': [
    true,
    {
        ignorePseudoClasses: ['global'],
    },
],
```

## Мотивация изменений
Тем кто не использует этот псевдо класс, такое изменение не должно доставлять проблем. 
А тем кто использует css модули не нужно будет дополнительно переопределять правило

**Comment by kiskv** [comment]
исправлено в 8.3.0
